name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=${GITHUB_WORKSPACE}/src" >> $GITHUB_ENV

    - name: Debug environment
      run: |
        echo "PYTHONPATH=$PYTHONPATH"
        echo "Working directory: $(pwd)"
        ls -R

    - name: Run tests
      run: pytest --maxfail=1 -v
