name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    # Step 3: Install dependencies
    - name: Install dependencies
      run: pip install -r requirements.txt

    # Step 4: Set PYTHONPATH to include the src directory
    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=${GITHUB_WORKSPACE}/src" >> $GITHUB_ENV

    # Step 5: Debugging step (optional)
    # Prints the current environment variables and directory structure for troubleshooting
    - name: Debug environment
      run: |
        echo "PYTHONPATH=$PYTHONPATH"
        echo "Working directory: $(pwd)"
        ls -R

    # Step 6: Run pytest
    - name: Run tests
      run: pytest --maxfail=1 -v
